version: '3.7'

services:
  api:
    container_name: poke-api
    image: node:18-alpine
    user: node
    working_dir: /home/node
    env_file: .env
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - .:/home/node
    command: /bin/sh -c "npm i && npm run start:dev"

  front:
    container_name: poke-front
    image: node:18-alpine
    user: node
    working_dir: /home/node
    env_file: ./public/.env
    ports:
      - "${PORT_FRONT:-3000}:3000"
    volumes:
      - ./public:/home/node
    command: /bin/sh -c "npm i && npm run start"

  db:
    container_name: poke-db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poke_db
    volumes:
      - poke-db-data:/var/lib/postgresql/data:rw

volumes:
  poke-db-data: {}
